#!/bin/tcsh
#
#$ -pe PE_8 8 
#$ -o job-$JOB_ID.out
#$ -e job-$JOB_ID.err
#$ -cwd
#$ -j y
#$ -m a
#$ -M wehnerj@mpip-mainz.mpg.de
#$ -N POLARRISATION
source /sw/linux/gromacs/5.1.2/bin/GMXRC
source /etc/profile.d/modules.csh
setenv MODULEPATH "/sw/linux/modules/modulefiles/"
module use -a "/people/thnfs/homes/wehnerj/privatemodules"
module load gaussian/g03
module load votca/git_cluster
# BASE DIRECTORY
set basedir=`pwd`
if ( ! -d /usr/scratch/wehnerj ) then
    mkdir /usr/scratch/wehnerj
endif

# JOB DIRECTORY
set jno=0
while ( -d job_$jno )
    set jno = `expr $jno + 1`
end
set jobdir="/usr/scratch/wehnerj/job_$jno"
mkdir -p $jobdir
rm -rf $jobdir/*
rsync -ar $basedir/* $jobdir

# EXECUTE HEAVY STUFF
cd $jobdir
xtp_tools -e exciton -o exciton.xml > exciton.log
cd ..

# SYNC BACK
rsync -au $jobdir/* $basedir
rm -rf $jobdir
